### PR TITLE
Fix "TypeError: this.types is not a function"

### LINKED ISSUE #3: TypeError: this.types is not a function
When I try to insert into the DB, I get the error TypeError: **this.types is not a function**

Entity looks like this

```
import { Model } from "@vuex-orm/core";
import { NumberField, OrmModel, StringField } from "vuex-orm-decorators";

@OrmModel("races")
export default class Race extends Model {
  @NumberField()
  public ID!: number;

  @StringField()
  public Name!: string;
}
```
store looks like this:

```
import Vue from "vue";
import Vuex from "vuex";
import { ORMDatabase } from "vuex-orm-decorators";

Vue.use(Vuex);

export default new Vuex.Store({
  .
  .
  .
  plugins: [ORMDatabase.install()]
});
```
Also, maybe this is a clue.... in Vuex-Orm, this.setters is returning a value, but this.setters('all') is returning undefined.

```
/**
 * Get all records.
 */
Model.all = function () {
   return this.getters('all')();
};
```
From seeing the undefined basic fields and functions, it seems like the vuex-orm database isn't getting set up correctly. Any ideas?

I also posted this on StackOverflow to see if other people have ideas. 
https://stackoverflow.com/questions/59020879/typeerror-this-types-is-not-a-function-when-using-vuex-orm-decorators

### PR DESCRIPTION
**Pull request by armaaar**
Fixes #3
The issue isn't from Vuex-ORM itself. By looking at [Single Table Inheritance](https://vuex-orm.github.io/vuex-orm/guide/model/single-table-inheritance.html#interacting-with-data) at the Vuex-ORM we can obviously see that `types` is a function but we clearly initialize it as an object in `model.ts`.

Also the `types` parameter can be `undefined` but there was no check if it was undefined before using it causing trouble.

I've fixed both issues built. I've to point that from my tiny dive into this package that it isn't fully ready yet for table inheritance features built in Vuex-ORM but still is great for simple use cases.

### CODE REVIEW

**Comment by JasonLandbridge** [comment]
@Scotley, Could this please be merged? My project is waiting for this before using Vuex-orm as the errors are blocking.

**Comment by Scotley** [comment]
Apologies for the delay.  I have actually reviewed this and will merge it now.

**Comment by JasonLandbridge** [comment]
Thank you!

**Comment by breynolds** [comment]
Thanks for this update. I was waiting for this too.

**Pull request merged**
