### PR TITLE
Fix path and upgrade version of @vuex-orm/core

### PR DESCRIPTION
**Pull request by tomas-kulhanek**
Is possible to check and fix it?

### CODE REVIEW

**Comment by TiBianMod** [comment]
Hi @tomas-kulhanek ,

can you use the next branch?

**Comment by tomas-kulhanek** [comment]
Omg, im so sorry 🤦

**Comment by TiBianMod** [comment]
NP, thanks mate.

I hope you don't have any issue with the next branch.

**Comment by tomas-kulhanek** [comment]
It`s ok :) thanks. I must study vuex-orm :)

**Comment by TiBianMod** [comment]
hehe, Good Luck :)

**Pull request closed without merging**
